import Nav from "./Nav";
import Head from "next/head";

export default function Layout({ home, children }) {
  return (
    <div>
      <nav className="navbar container-fluid my-nav">
        <Head>
          <meta
            name="Super Hero Encyclopedia"
            content="Generated by create next app"
          />
          <link rel="icon" href="/images/Logosvg.ico" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
            crossorigin="anonymous"
          />
        </Head>
        <Nav />
      </nav>
      <main>{children}</main>
    </div>
  );
}
